language: node_js

node_js:
  - stable

cache: npm

install:
  - npm install

stages:
  - name: test
  - name: deploy

script:
  - node --version
  - npm --version
  - echo "Testing Started ..."
  - npm test
  - echo "Testing Finished."
  - echo "NPM Deploying Started ..."
  - npm version
  - npm run prepublish
  - npm run predeploy
  - npm run deploy
  - echo "NPM Building Finished."

deploy:
  provider: npm
  email: "${GITHUB_TOKEN}"
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true
  on:
    all_branches: true


