language: node_js

node_js:
  - stable

cache: yarn

install:
  - yarn install

stages:
  - name: test
  - name: deploy

script:
  - node --version
  - yarn --version
  - echo "Testing Started ..."
  - yarn test
  - echo "Testing Finished."
  - echo "Yarn Deploying Started ..."
  - yarn run prepublish
  - yarn run predeploy
  - yarn run deploy
  - echo "Yarn Building Finished."

deploy:
  provider: npm
  email: "${GITHUB_TOKEN}"
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true
  on:
    all_branches: true


